# Generated by Django 5.2 on 2025-09-01 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("mainHashtag", models.CharField()),
                ("sentiment", models.JSONField(default=dict)),
                (
                    "inclination",
                    models.CharField(
                        choices=[
                            ("Çok Olumlu", "Çok Olumlu"),
                            ("Olumlu", "Olumlu"),
                            ("Nötr", "Nötr"),
                            ("Olumsuz", "Olumsuz"),
                            ("Çok Olumsuz", "Çok Olumsuz"),
                        ],
                        default="",
                    ),
                ),
                ("hashtags_list", models.JSONField(default=dict)),
                ("topics", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("İç Anadolu Bölgesi", "İç Anadolu Bölgesi"),
                            ("Doğu Anadolu Bölgesi", "Doğu Anadolu Bölgesi"),
                            ("Güneydoğu Anadolu Bölgesi", "Güneydoğu Anadolu Bölgesi"),
                            ("Ege Bölgesi", "Ege Bölgesi"),
                            ("Marmara Bölgesi", "Marmara Bölgesi"),
                            ("Akdeniz Bölgesi", "Akdeniz Bölgesi"),
                            ("Karadeniz Bölgesi", "Karadeniz Bölgesi"),
                        ]
                    ),
                ),
                ("d", models.CharField()),
                ("weekly_trend", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataofPlatforms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("posts", models.PositiveBigIntegerField()),
                ("mainTopic", models.CharField()),
                ("mainHashtag", models.CharField()),
                ("sentiment", models.JSONField(default=dict)),
                (
                    "inclination",
                    models.CharField(
                        choices=[
                            ("Çok Olumlu", "Çok Olumlu"),
                            ("Olumlu", "Olumlu"),
                            ("Nötr", "Nötr"),
                            ("Olumsuz", "Olumsuz"),
                            ("Çok Olumsuz", "Çok Olumsuz"),
                        ],
                        default="",
                    ),
                ),
                ("hashtags", models.JSONField(default=dict)),
                ("topics", models.JSONField(default=dict)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="province_data.city",
                    ),
                ),
            ],
        ),
    ]
