# Generated by Django 5.2 on 2025-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="mainHashtag",
            field=models.CharField(blank=True, null=True),
        ),
    ]
