# Generated by Django 5.2 on 2025-09-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0002_alter_city_mainhashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="sentiment",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
