# Generated by Django 5.2 on 2025-09-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0003_alter_city_sentiment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="topics",
            new_name="topics_list",
        ),
    ]
