# Generated by Django 5.2 on 2025-09-02 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0004_rename_topics_city_topics_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalDataLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("topics_list", models.JSONField(default=dict)),
                ("posts", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="dataofplatforms",
            old_name="hashtags",
            new_name="hashtags_list",
        ),
        migrations.RenameField(
            model_name="dataofplatforms",
            old_name="topics",
            new_name="topics_list",
        ),
        migrations.RemoveField(
            model_name="city",
            name="weekly_trend",
        ),
        migrations.AddField(
            model_name="dataofplatforms",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
