# Generated by Django 5.2 on 2025-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0005_nationaldatalog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                choices=[
                    ("X (Twitter)", "X (Twitter)"),
                    ("Next Sosyal", "Next Sosyal"),
                    ("Instagram", "Instagram"),
                ],
                max_length=40,
            ),
        ),
    ]
