# Generated by Django 5.2 on 2025-09-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0006_alter_city_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationaldatalog",
            name="topics_list",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
