# Generated by Django 5.2 on 2025-09-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0007_alter_nationaldatalog_topics_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationaldatalog",
            name="posts",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
