# Generated by Django 5.2 on 2025-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("province_data", "0008_alter_nationaldatalog_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="hashtags_list",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="dataofplatforms",
            name="hashtags_list",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="dataofplatforms",
            name="mainHashtag",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataofplatforms",
            name="mainTopic",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataofplatforms",
            name="sentiment",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="dataofplatforms",
            name="topics_list",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
